### ISSUE TITLE
Acceleration vector is visible when there is no acceleration

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#169]
1. 2nd or 4th screen,
2. Enable both Velocity and Acceleration vectors.
3. Attach a mass and let it oscillate.
4. Press the mass's "stop" button. There will be no vectors (good!)
5. Click the mass

You will then see an acceleration vector, though the mass is not moving and at equilibrium.

![screen shot 2017-11-17 at 2 08 51 pm](https://user-images.githubusercontent.com/5863899/32969073-dd37c138-cba0-11e7-8281-1f76c952cc8a.png)

If you do this from a fresh browser tab, and do step 2 after step 4 instead, you will get #165

![screen shot 2017-11-17 at 2 11 48 pm](https://user-images.githubusercontent.com/5863899/32969180-4da30d6a-cba1-11e7-9df7-888273960a29.png)

Seen on macOS 10.13.1 Chrome. For phetsims/QA#67.

URL: https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.28/masses-and-springs_en.html
Version: 1.0.0-dev.28 2017-11-10 19:03:33 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4918cd72","branch":"master"},"babel":{"sha":"fcbcac44","branch":"master"},"brand":{"sha":"53cf227b","branch":"master"},"chipper":{"sha":"ca18330e","branch":"master"},"dot":{"sha":"4a1ddd12","branch":"master"},"griddle":{"sha":"6e1983be","branch":"master"},"joist":{"sha":"f34dc747","branch":"master"},"kite":{"sha":"e4c0b773","branch":"master"},"masses-and-springs":{"sha":"9d24969e","branch":"master"},"phet-core":{"sha":"ad21faf3","branch":"master"},"phetcommon":{"sha":"d957aefc","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"8e5b0892","branch":"master"},"scenery-phet":{"sha":"11c7fdb3","branch":"master"},"sherpa":{"sha":"5079b265","branch":"master"},"sun":{"sha":"71295bf0","branch":"master"},"tandem":{"sha":"547eb84d","branch":"master"},"twixt":{"sha":"13905577","branch":"master"}}

**Comment by Denz1994** [comment]
Was able to track this bug down and removed toggling the visibility during vector size updates. There were some checks that weren't being hit outside of the vector updates.

**Comment by phet-steele** [comment]
I think this is fixed, thanks.

**Comment by CWilson4960** [comment]
This issue is occurring again in rc.4
phetsims/QA/issues/180
related to phetsims/masses-and-springs/issues/165 also reopening.
Steps to reproduce:
Load sim
Go to 2nd screen
Check slo mo (option, just exactly what I did)
Hang 100g mass
Stop Mass
Check net force and acceleration (occurs with just acceleration too)
Macbook Pro 2012, OS Sierra 10.12.6
Chrome Version 68.0.3440.106 (Official Build) (64-bit)
![mas vectors thingy](https://user-images.githubusercontent.com/31217926/44870305-1d5ea000-ac4d-11e8-8b4b-8038de6b122d.jpeg)
![vectors thingy 3](https://user-images.githubusercontent.com/31217926/44870307-1d5ea000-ac4d-11e8-9c96-667dbca00847.jpeg)

URL: https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-rc.4/phet/masses-and-springs_all_phet.html
Version: 1.0.0-rc.4 2018-08-24 22:56:24 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Language: en-US
Window: 941x584
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"37d5839c","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"bc1f66fe","branch":"HEAD"},"dot":{"sha":"bd4d7035","branch":"HEAD"},"griddle":{"sha":"7be25724","branch":"HEAD"},"joist":{"sha":"8da47b06","branch":"HEAD"},"kite":{"sha":"3b76b24a","branch":"HEAD"},"masses-and-springs":{"sha":"0cd2d603","branch":"HEAD"},"phet-core":{"sha":"e0cec207","branch":"HEAD"},"phet-io":{"sha":"e5c7148f","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"5204ea8e","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ccaaaa4b","branch":"HEAD"},"phet-io-wrappers":{"sha":"f3701e8d","branch":"HEAD"},"phetcommon":{"sha":"80414edb","branch":"HEAD"},"query-string-machine":{"sha":"1f2322e4","branch":"HEAD"},"scenery":{"sha":"3b05db54","branch":"HEAD"},"scenery-phet":{"sha":"f37bff38","branch":"HEAD"},"sherpa":{"sha":"ded365aa","branch":"HEAD"},"sun":{"sha":"00b9c74c","branch":"HEAD"},"tandem":{"sha":"3e1c8fd3","branch":"HEAD"},"twixt":{"sha":"050e8f19","branch":"HEAD"}}

**Comment by Denz1994** [comment]
Can you test on RC 1.0 branch for this fix @KatieWoe?

**Comment by KatieWoe** [comment]
@Denz1994 I'm unclear as to what you mean.  Do you mean this link: https://phet-dev.colorado.edu/html/masses-and-springs/1.0.0-rc.4/

**Comment by KatieWoe** [comment]
This still occurs on master and in the link above. @Denz1994 
![update](https://user-images.githubusercontent.com/41024075/45385215-660f4500-b5cd-11e8-8c8a-c4adce4c7793.PNG)

**Comment by phet-steele** [comment]
https://github.com/phetsims/masses-and-springs/issues/165#issuecomment-420413699

**Comment by Denz1994** [comment]
The above fixes have been applied to https://phet-dev.colorado.edu/html/masses-and-springs/1.0.0-rc.5/phet/masses-and-springs_en_phet.html. Could you use this link to test @KatieWoe?

If the fixes above solve the bug, I will cherry-pick the commits into master.

**Comment by KatieWoe** [comment]
Looks good to me.

**Comment by Denz1994** [comment]
Fixes cherry-picked into master #169 #165. Closing.
