### ISSUE TITLE
Spring thickness in second scene of intro screen initially appears incorrect

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/masses-and-springs#314]
**Test device:**
Dell and hp Laptop
**Operating System:**
Windows 10 and 7
**Browser:**
Chrome and Firefox
**Problem description:**
For phetsims/QA/issues/165
When using the second scene in the intro screen that allows students to compare different lengths of spring, the initial thickness of the left spring is incorrect.  It has the spring constant set as the constant parameter, but shows a thickness that is constant instead.  When "thickness" is selected as constant, and then spring constant is selected again this corrects itself.  It also is corrected if the player uses the orange reset button.  It should be noted that the sim behavior does seem correct, even when the visuals are not.
**Steps to reproduce:**
1. Go to the Intro screen (**Important:** You must start this from a new load.  It may be best to refresh the page)
2. Select the second scene with the different length springs
3. Note the thickness of the left spring.  You may also use masses to determine that the two springs do seem to have the same spring constant
4. Select the "Thickness" option for a constant variable.  Note the appropriate change in behavior
5. Reselect the "Spring Constant" option and note the change in appearance of the spring.  Behavior still seems correct.
6. Hit the orange reset button.  You will note that the thin left spring remains.  It will also appear even if the reset button is used before the thin spring appears as described above.

**Screenshots:**
![thickness](https://user-images.githubusercontent.com/41024075/43967271-3f808c42-9c81-11e8-83bd-5f41550300c5.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Masses and Springs‬
URL: https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-rc.3/phet/masses-and-springs_all_phet.html
Version: 1.0.0-rc.3 2018-08-08 21:38:04 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36
Language: en-US
Window: 1536x737
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"37d5839c","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"bc1f66fe","branch":"HEAD"},"dot":{"sha":"bd4d7035","branch":"HEAD"},"griddle":{"sha":"7be25724","branch":"HEAD"},"joist":{"sha":"8da47b06","branch":"HEAD"},"kite":{"sha":"3b76b24a","branch":"HEAD"},"masses-and-springs":{"sha":"b0f63e4a","branch":"HEAD"},"phet-core":{"sha":"e0cec207","branch":"HEAD"},"phet-io":{"sha":"e5c7148f","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"5204ea8e","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ccaaaa4b","branch":"HEAD"},"phet-io-wrappers":{"sha":"f3701e8d","branch":"HEAD"},"phetcommon":{"sha":"80414edb","branch":"HEAD"},"query-string-machine":{"sha":"1f2322e4","branch":"HEAD"},"scenery":{"sha":"3b05db54","branch":"HEAD"},"scenery-phet":{"sha":"f37bff38","branch":"HEAD"},"sherpa":{"sha":"ded365aa","branch":"HEAD"},"sun":{"sha":"00b9c74c","branch":"HEAD"},"tandem":{"sha":"3e1c8fd3","branch":"HEAD"},"twixt":{"sha":"050e8f19","branch":"HEAD"}}

</details>

**Comment by Denz1994** [comment]
Great find @KatieWoe. Can you check the bug is fixed in master? Also @arouinfar can you check to make sure this is the behavior we want. I do think it is an improvement.

**Comment by arouinfar** [comment]
Nice one @KatieWoe! @Denz1994 master is behaving pretty nicely to me, but I'll let @KatieWoe verify that the original issues has been addressed.

**Comment by KatieWoe** [comment]
Looks good in master.

**Comment by arouinfar** [comment]
Great! I'll go ahead and close.

**Comment by KatieWoe** [comment]
This issue is back in  https://github.com/phetsims/QA/issues/188#event-1850450915

**Comment by Denz1994** [comment]
Please confirm this is corrected in [1.0.0-rc.7](https://phet-dev.colorado.edu/html/masses-and-springs/1.0.0-rc.7/phet/masses-and-springs_en_phet.html) @KatieWoe and if so, you can close this issue.

**Comment by phet-steele** [comment]
The fix is now in 1.0 and looks fine!

**Comment by KatieWoe** [comment]
@Denz1994 it looks fixed in that link but now https://github.com/phetsims/masses-and-springs/issues/329 looks unfixed there.

**Comment by phet-steele** [comment]
Oh wow I've never seen two opposite commits on the same line where each fixes its own bug but causes another. https://github.com/phetsims/masses-and-springs/commit/d4d6abd49d75943acd6f9ac245b8cba6b46db776 and https://github.com/phetsims/masses-and-springs/commit/aaba5ccc287639c876f9bedb43611ceb775bbc50

**Comment by Denz1994** [comment]
Okay, this is probably why it wasn't included in rc.6. Working on a new solution. Thanks for the notice @KatieWoe.

**Comment by Denz1994** [comment]
@KatieWoe Can you review [1.0.0-rc.8](https://phet-dev.colorado.edu/html/masses-and-springs/1.0.0-rc.8/phet/masses-and-springs_en_phet.html) for an applied fix for this issue and #329? If fixed, I'll cherry-pick the changes into master.

**Comment by KatieWoe** [comment]
@Denz1994 looks good.

**Comment by Denz1994** [comment]
Fixes cherry-picked into master. Closing.
